name: 🚀 Despliegue Automático a cPanel (DAPEA)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  web-deploy:
    name: 🌐 Transferir Archivos por FTP
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Checkout del Código
        uses: actions/checkout@v4

      - name: 🚀 Sincronizar por FTP a Servidor de Producción
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          exclude: |
            **/.git*
            **/.git*/**
            .gitignore
            README.md
